import { inputProps } from "./doctor-worker-form";
export const requestFormInputes: inputProps[] = [
  {
    id: '1',
    type: 'text',
    inputType: 'select',
    label: 'Blood Type',
    placeholder: 'Enter blood type',
    name: 'blood_type',
    disabled: true,
  },
  {
    id: '2',
    type: 'text',
    inputType: 'input',
    label: 'Quantity',
    placeholder: 'Enter quantity',
    name: 'quantity',
    disabled: false,
  },
  {
    id: '3',
    type: 'text',
    inputType: 'input',
    label: 'Institution ID',
    placeholder: 'Enter institution ID',
    name: 'institution_id',
    disabled: true,
  }
];
export const campsFormsvalues: inputProps[] = [
  {
    id: '1',
    type: 'text',
    inputType: 'input',
    label: 'Camp Name',
    placeholder: 'Enter camp name',
    name: 'name',
    disabled: false,
  },
  {
    id: '3',
    type: 'date',
    inputType: 'date',
    label: 'Start Date',
    placeholder: 'Select start date',
    name: 'date',
    disabled: false,
  },
  {
    id: '4',
    type: 'date',
    inputType: 'date',
    label: 'End Date',
    placeholder: 'Select end date',
    name: 'end_date',
    disabled: false,
  },
  {
    id: '5',
    type: 'text',
    inputType: 'input',
    label: 'Institution ID',
    placeholder: 'Enter institution ID',
    name: 'institution_id',
    disabled: true,
  },
  {
    id: '6',
    type: 'text',
    inputType: 'input',
    label: 'Organized By',
    placeholder: 'Enter organizer name',
    name: 'organized_by',
    disabled: true,
  },
  {
    id: '7',
    type: 'text',
    inputType: 'input',
    label: 'Address Line 1',
    placeholder: 'Enter address line 1',
    name: 'address_line1',
    disabled: false,
  },
  {
    id: '8',
    type: 'text',
    inputType: 'input',
    label: 'State',
    placeholder: 'Enter state',
    name: 'state',
    disabled: false,
  },
  {
    id: '9',
    type: 'text',
    inputType: 'input',
    label: 'City',
    placeholder: 'Enter city',
    name: 'city',
    disabled: false,
  },
  {
    id: '10',
    type: 'text',
    inputType: 'input',
    label: 'Country',
    placeholder: 'Enter country',
    name: 'country',
    disabled: false,
  },
  {
    id: '11',
    type: 'text',
    inputType: 'input',
    label: 'Postal Code',
    placeholder: 'Enter postal code',
    name: 'postalCode',
    disabled: false,
  },
  {
    id: '12',
    type: 'text',
    inputType: 'input',
    label: 'About Camp',
    placeholder: 'Write about the camp',
    name: 'about',
    disabled: false,
  },
];
